apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: web
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXbHVZVzkxYVcxb09tUmphM0pmY0dGMFgyNVZaamxFV1VveE5DMTBVMUY0UjJsQmFtNXhSVko2VVd4MVVRPT0iCgkJfQoJfQp9
