apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts: # Mount the PVC to the container
            - name: mysql-storage
              mountPath: /var/lib/mysql # MySQL default data directory
      volumes: # Define the PVC volume
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
